name: Deploy to k8s cluster

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      name:
        description: "Manual workflow name"
        required: true

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=tag::$(cat VERSION)

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Get cluster config
        run: doctl k8s cluster kubeconfig show convoy > .kubeconfig

      - name: Push image to DigitalOcean Container Registry
        run: helm --debug upgrade --install --version ${{ steps.get_version.outputs.tag }} convoy "https://github.com/frain-dev/helm-charts/releases/download/convoy-v0.7/convoy-v0.7.tgz" --kubeconfig=.kubeconfig --namespace=dev --set image.repository=ghcr.io/$GITHUB_REPOSITORY,image.tag=latest
